### ISSUE TITLE
feature suggestion client block place or setblock

### ISSUE THREAD

**Issue by Rav115** [TheVoidBlock/ClientGive#1]
It could be its own mod or just extra feature in this one
should make command like /csetblock ^ ^1 ^3 stone or /cplaceghost toggle to place ghost blocks 
i guess also ghost air breaking but might also need some command to refresh/remove the ghost blocks

**Comment by TheVoidBlock** [comment]
I added /vsetblock and /vghostplacement. You can just right click the ghost blocks (without ghost placement on) to update them. I also rebranded the mod if you're confused. [Here](https://modrinth.com/mod/voidcommands/version/1.1+1.21) is a link to the version
