### ISSUE TITLE
feature suggesting ghostblock vanilla-slash-fill-like command arguments

### ISSUE THREAD

**Issue by TT275101** [TheVoidBlock/ClientGive#2]
it will be really helpful if ghostblock filling command can have arguments like "replace" or "keep", as in vanilla command /fill <pos1> <pos2> minecraft:stone --->[replace\keep\hollow]<----these
also, will the ghost entity feature be added into the 1.21.0 version mod update?

**Comment by TheVoidBlock** [comment]
I added a command for filling an area with blocks. It has hollow, keep, outline, and replace. It doesn't have destroy.

**Comment by TheVoidBlock** [comment]
I occasionally back-port the mod. I probably will after next release.
